# rerun VA GOV poll averaging script daily
name: va_gov_update

# run every day at 12
on: 
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:
    
jobs:
  update_readme:
    
    # add runner
    runs-on: windows-latest
    
    # do each step in sequenc
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Load packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("ggtext")'
          R -e 'install.packages("extrafont")'
          
      - name: Restore Packages
        shell: Rscript {0}
        run: |
          if(!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      
      - name: Run VA Update
        run: Rscript 2021.10.01-virginia_governors_race/scripts/va_poll_wrangle.R
        
      - name: Commit files
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m "Update VA GOV via GitHub Actions" -a
          
      - name: Push update
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN}}