# rerun VA GOV poll averaging script daily
name: va_gov_update

# run every day at 12
on: 
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    
jobs:
  update_readme:
    
    # add runner
    runs-on: macos-latest
    
    # load repo & install R
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      
      # setup R
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("lubridate")'
          R -e 'install.packages("patchwork")'
          R -e 'install.packages("ggtext")'
      
      # run R script
      - name: Run VA Update
        run: Rscript 2021.10.01-virginia_governors_race/scripts/va_poll_wrangle.R
        
      # add images from script
      - name: Commit files
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m "Update VA GOV via GitHub Actions" -a
          
      # push 
      - name: Push update
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN}}